Feature/data range selector
Edds390/solarnetwork-aggregated-dashboard pull request #23
Opened 2018-03-27 21:40 UTC by SeoyoungC

2018-03-27 21:48 UTC, elisalter commented
Resolve the conflicts and repush the changes 👍

2018-03-27 21:50 UTC, NathanHenderson commented on src/components/DashboardPanel/DashboardPanel.js
> +      startDate: moment(this.props.startDate).format('YYYY-MM-DD'),
Abstract the date format so that we are not using hard coded strings in multiple places

2018-03-27 21:55 UTC, Edds390 approved these changes
Date picker looking great. Open an issue for handling data where a node has >1000 observations.

2018-03-27 21:58 UTC, elisalter requested changes
A few small changes to clean up readability with moment objects, and some es6 constructs.

2018-03-27 21:58 UTC, elisalter commented on src/components/DashboardPanel/DashboardPanel.js
>    selectedNodes: PropTypes.object,
For Moment.js prop-types we should be using `PropTypes.instanceOf(Date)` instead of `PropTypes.object`, as it is more specific.

2018-03-27 21:58 UTC, elisalter commented on src/components/Home/Home.js
> +import * as moment from 'moment';
`import moment from 'moment';` should work here

2018-03-27 21:58 UTC, elisalter commented on src/components/Home/Home.js
> +              state: { selectedNodes: selectedNodes, startDate: startDate, endDate: endDate  }
with es6 we can do not need to use key: value, where the key and the value are identical. We can just state the key, so this line can be refactored to:

state: { selectedNodes, startDate, endDate  }

2018-03-27 21:58 UTC, elisalter commented on src/components/pages/DashboardPage/DashboardPage.js
> +        <DashboardPanel selectedNodes={this.state.selectedNodes} startDate={this.state.startDate} endDate={this.state.endDate} />
Could try deconstructing state at the start of the render method 👍 probably best to do this once we start calling `this.state` on >=3 objects

2018-03-28 01:12 UTC, elisalter approved these changes
Looks good! We can change the `moment` import in `home.js` at a later date 👍

2018-03-28 05:05 UTC, Edds390 commented
May require labels in the future for more intuitive interface but other than that looks good!

2018-03-28 05:07 UTC, SeoyoungC commented
Cheers @Edds390, I'll raise an issue for the labels

2018-03-28 05:07 UTC, merged