Extracting the data values processing & displaying totals
Edds390/solarnetwork-aggregated-dashboard pull request #37
Opened 2018-03-29 23:38 UTC by sejpat25

The components used to display this information had to change according to our dashboard display. Now data associated with the nodes are received and processed to display the maximum, accumulated sum and average of a particular value associated to a node.

2018-03-30 00:07 UTC, Edds390 requested changes
Very good commenting and easy to follow code structure. Minor changes to import statements requested. Also, the paragraph bodies of the statistics are using the wrong font:
![image](https://user-images.githubusercontent.com/21207045/38119075-8f13f498-341b-11e8-8ef0-373f0b5c0c82.png)
Override using css requested.

2018-03-30 00:07 UTC, Edds390 commented on src/components/DataTable/DropDownNodeMenu/DropDownNodeMenu.js
>  import MenuItem from 'material-ui/MenuItem';
Remove unused imports

2018-03-30 00:07 UTC, Edds390 commented on src/components/DataTable/DropDownNodeMenu/DropDownNodeMenu.js
>  import Paper from 'material-ui/Paper';
absolute imports before relative imports

2018-03-31 03:12 UTC, Edds390 approved these changes

2018-03-31 09:52 UTC, Edds390 commented
Closes [Issue 21](https://github.com/Edds390/solarnetwork-aggregated-dashboard/issues/21)

2018-03-31 09:58 UTC, KenneyC approved these changes
Tested on your branch, looks good to me 👍 Fantastic work!

2018-03-31 10:03 UTC, merged